package edu.harvard.mcz.imagecapture.entity


import java.io.Serializable

// Generated Jan 23, 2009 8:12:35 AM by Hibernate Tools 3.2.2.GA
/**
 * Collector generated by hbm2java
 */
class Collector : Serializable, Cloneable, Comparable<Any?>, Cloneable {
    var collectorId: Long? = null
    private var specimen: Specimen? = null
    var collectorName: String? = null

    constructor() {}
    constructor(specimen: Specimen?) {
        this.specimen = specimen
    }

    constructor(specimen: Specimen?, collectorName: String?) {
        this.specimen = specimen
        this.collectorName = collectorName
    }

    fun getSpecimen(): Specimen? {
        return specimen
    }

    fun setSpecimen(specimen: Specimen?) {
        this.specimen = specimen
    }

    public override fun clone(): Any {
        return Collector(specimen, collectorName)
    }

    override fun compareTo(o: Any?): Int {
        if (o !is Collector) {
            throw UnsupportedOperationException("Cannot compare Collector to " + o.javaClass)
        }
        return collectorName!!.compareTo((o as Collector?)!!.collectorName)
    }

    companion object {
        private const val serialVersionUID = 4879266496355071312L
    }
}
