package edu.harvard.mcz.imagecapture.entity


import edu.harvard.mcz.imagecapture.data.MetadataRetriever
import edu.harvard.mcz.imagecapture.entity.ICImage
import java.io.Serializable

// Generated Jan 23, 2009 8:12:35 AM by Hibernate Tools 3.2.2.GA
/**
 * ICImage generated by hbm2java
 */
class ICImage : Serializable {
    var imageId: Long? = null
    private var specimen: Specimen? = null
    private var rawBarcode: String? = null
    private var rawExifBarcode: String? = null
    var filename: String? = null
    var rawOcr: String? = null
        set(rawOcr) {
            field = rawOcr
            if (this.rawOcr != null && this.rawOcr!!.length > MetadataRetriever.getFieldLength(ICImage::class.java, "rawOcr")) {
                field = this.rawOcr!!.substring(0, MetadataRetriever.getFieldLength(ICImage::class.java, "rawOcr"))
            }
        }
    var path: String? = null
    var uri: String? = null
    var templateId: String? = null
    /**
     * @return the drawerNumber
     */
    /**
     * @param drawerNumber the drawerNumber to set
     */
    var drawerNumber: String? = null
        set(drawerNumber) {
            field = drawerNumber
            if (this.drawerNumber != null && this.drawerNumber!!.length > MetadataRetriever.getFieldLength(ICImage::class.java, "drawerNumber")) {
                field = this.drawerNumber!!.substring(0, MetadataRetriever.getFieldLength(ICImage::class.java, "drawerNumber"))
            }
        }
    /**
     * @return the md5sum
     */
    /**
     * @param md5sum the md5sum to set
     */
    var md5sum: String? = null

    constructor() {}
    constructor(specimen: Specimen?) {
        this.specimen = specimen
    }

    constructor(specimen: Specimen?, rawBarcode: String?, rawExifBarcode: String?, filename: String?,
                rawOcr: String?, path: String?, uri: String?, templateId: String?, drawerNumber: String?) {
        this.specimen = specimen
        this.rawBarcode = rawBarcode
        this.rawExifBarcode = rawExifBarcode
        this.filename = filename
        rawOcr = rawOcr
        this.path = path
        this.uri = uri
        this.templateId = templateId
        drawerNumber = drawerNumber
    }

    fun getSpecimen(): Specimen? {
        return specimen
    }

    fun setSpecimen(specimen: Specimen?) {
        this.specimen = specimen
    }

    fun getRawBarcode(): String? {
        return rawBarcode
    }

    fun setRawBarcode(rawBarcode: String?) {
        this.rawBarcode = rawBarcode
        if (this.rawBarcode != null && this.rawBarcode!!.length > MetadataRetriever.getFieldLength(ICImage::class.java, "rawBarcode")) {
            this.rawBarcode = this.rawBarcode!!.substring(0, MetadataRetriever.getFieldLength(ICImage::class.java, "rawBarcode"))
        }
    }

    fun getRawExifBarcode(): String? {
        return rawExifBarcode
    }

    fun setRawExifBarcode(rawExifBarcode: String?) {
        this.rawExifBarcode = rawExifBarcode
        if (this.rawExifBarcode != null && this.rawExifBarcode!!.length > MetadataRetriever.getFieldLength(ICImage::class.java, "rawExifBarcode")) {
            this.rawExifBarcode = this.rawExifBarcode!!.substring(0, MetadataRetriever.getFieldLength(ICImage::class.java, "rawExifBarcode"))
        }
    }

    companion object {
        private const val serialVersionUID = -6798658217903637142L
    }
}
