package edu.harvard.mcz.imagecapture.entity


import java.io.Serializable
import java.util.*

// Generated Jan 23, 2009 8:12:35 AM by Hibernate Tools 3.2.2.GA
/**
 * Number generated by hbm2java
 */
class Number : Serializable, Cloneable, Comparable<Any?>, Cloneable {
    var numberId: Long? = null
    private var specimen: Specimen? = null
    var number: String? = null
    var numberType: String? = null

    constructor() {}
    constructor(specimen: Specimen?) {
        this.specimen = specimen
    }

    constructor(specimen: Specimen?, number: String?, numberType: String?) {
        this.specimen = specimen
        this.number = number
        this.numberType = numberType
    }

    fun getSpecimen(): Specimen? {
        return specimen
    }

    fun setSpecimen(specimen: Specimen?) {
        this.specimen = specimen
    }

    public override fun clone(): Any {
        return Number(specimen, number, numberType)
    }

    override fun compareTo(o: Any?): Int {
        if (o !is Number) {
            throw UnsupportedOperationException("Cannot compare Number to " + o.javaClass)
        }
        return number!!.compareTo((o as Number?)!!.number)
    }

    companion object {
        private const val serialVersionUID = -7325097435841353006L//result.add("MCZ Slide Number");
        //result.add("Drawer Number");
//result.add("Lycaenidae Morphology Ref.");
//result.add("MCZ Butterfly Exhibit, 2000");
        //New: add “GBIFCH barcode tag”; “CSCF barcode tag”; “Swiss Grid”
//New: remove “MCZ Slide number”; “Drawer number”; “Lycaenidae Morphology Ref.”; “MCZ Butterfly Exhibit, 2000”.
        val numberTypeValues: MutableList<String?>
            get() {
                val result: MutableList<String?> = ArrayList()
                result.add("")
                result.add("Unknown")
                result.add("Species Number")
                result.add("Collector Number")
                result.add("Collection Number")
                //result.add("MCZ Slide Number");
                result.add("Genitalia Preparation")
                result.add("DNA Sample Number")
                //result.add("Drawer Number");
//result.add("Lycaenidae Morphology Ref.");
//result.add("MCZ Butterfly Exhibit, 2000");
                result.add("GBIFCH barcode tag")
                result.add("CSCF barcode tag")
                result.add("Swiss Grid coordinates")
                return result
            }
    }
}
