package edu.harvard.mcz.imagecapture.entity


import edu.harvard.mcz.imagecapture.ImageCaptureProperties
import edu.harvard.mcz.imagecapture.Singleton
import edu.harvard.mcz.imagecapture.data.MetadataRetriever
import edu.harvard.mcz.imagecapture.entity.Specimen
import edu.harvard.mcz.imagecapture.entity.fixed.NatureOfId
import edu.harvard.mcz.imagecapture.entity.fixed.WorkFlowStatus
import edu.harvard.mcz.imagecapture.exceptions.SaveFailedException
import edu.harvard.mcz.imagecapture.lifecycle.SpecimenPartLifeCycle
import org.apache.commons.logging.LogFactory
import java.io.Serializable
import java.util.*

// Generated Jan 23, 2009 8:12:35 AM by Hibernate Tools 3.2.2.GA
/**
 * Specimen generated by hbm2java
 */
class Specimen : Serializable {
    var specimenId: Long? = null
    var barcode: String? = null
    private var drawerNumber: String? = null
    var typeStatus // Types only
            : String? = null
    var typeNumber // Types only, raw number for crosscheck
            : Long? = null
    var citedInPublication // (title) Types only
            : String? = null
    //private String citedInPublicationPage;  // Types only
//private String citedInPublicationYear;  // Types only
    var features: String? = null
    var family: String? = null
        set(family) {
            field = family
            if (this.family != null && this.family!!.length > MetadataRetriever.getFieldLength(Specimen::class.java, "Family")) {
                field = this.family!!.substring(0, MetadataRetriever.getFieldLength(Specimen::class.java, "Family"))
            }
            if (this.family != null) {
                field = this.family!!.trim { it <= ' ' }
            }
        }
    private var subfamily: String? = null
    private var tribe: String? = null
    private var genus: String? = null
    private var specificEpithet: String? = null
    private var subspecificEpithet: String? = null
    private var infraspecificEpithet: String? = null
    private var infraspecificRank: String? = null
    private var authorship: String? = null
    private var unNamedForm: String? = null
    //private String identificationQualifier;
    var identifiedBy: String? = null
    /**
     * @return the natureOfId
     */
    /**
     * @param natureOfId the natureOfId to set
     */
    var natureOfId: String? = null
    /**
     * @return the dateIdentified
     */
    /**
     * @param dateIdentified the dateIdentified to set
     */
    var dateIdentified: String? = null
    /**
     * @return the identificationRemarks
     */
    /**
     * @param identificationRemarks the identificationRemarks to set
     */
    var identificationRemarks: String? = null
    /**
     * @return the higherGeography
     */
    /**
     * @param higherGeography the higherGeography to set
     */
    var higherGeography: String? = null
    var country: String? = null
    var primaryDivison: String? = null
    var specificLocality: String? = null
    var verbatimLocality: String? = null
    /**
     * @return the verbatimCollector
     */
    /**
     * @param verbatimCollector the verbatimCollector to set
     */
    var verbatimCollector: String? = null
    /**
     * @return the verbatimCollection
     */
    /**
     * @param verbatimCollection the verbatimCollection to set
     */
    var verbatimCollection: String? = null
    /**
     * @return the verbatimNumbers
     */
    /**
     * @param verbatimNumbers the verbatimNumbers to set
     */
    var verbatimNumbers: String? = null
    /**
     * @return the verbatimUnclassifiedText
     */
    /**
     * @param verbatimUnclassifiedText the verbatimUnclassifiedText to set
     */
    var verbatimUnclassifiedText: String? = null
    /**
     * @return the verbatimClusterIdentifier
     */
    /**
     * @param verbatimClusterIdentifier the verbatimClusterIdentifier to set
     */
    var verbatimClusterIdentifier: String? = null
    /**
     * @return the externalWorkflowProcess
     */
    /**
     * @param externalWorkflowProcess the externalWorkflowProcess to set
     */
    var externalWorkflowProcess: String? = null
    /**
     * @return the externalWorkflowDate
     */
    /**
     * @param externalWorkflowDate the externalWorkflowDate to set
     */
    var externalWorkflowDate: Date? = null
    /**
     * @return the minimum_elevation
     */
    /**
     * @param minimum_elevation the minimum_elevation to set
     */
    // private String verbatimElevation;   // removed
    var minimum_elevation: Long? = null
    /**
     * @return the maximum_elevation
     */
    /**
     * @param maximum_elevation the maximum_elevation to set
     */
    var maximum_elevation: Long? = null
    /**
     * @return the elev_units
     */
    /**
     * @param elev_units the elev_units to set
     */
    var elev_units: String? = null
    var collectingMethod: String? = null
    var isoDate: String? = null
    var dateNos: String? = null
    var dateEmerged: String? = null
    var dateEmergedIndicator: String? = null
    var dateCollected: String? = null
    var dateCollectedIndicator: String? = null
    var collection: String? = null
    var specimenNotes: String? = null
    var lifeStage: String? = null
    var sex: String? = null
    // private String preparationType;
    var habitat: String? = null
    /**
     * @return the microhabitat
     */
    /**
     * @param microhabitat the microhabitat to set
     */
    var microhabitat: String? = null
    var associatedTaxon: String? = null
    var questions: String? = null
    var inferences: String? = null
    var locationInCollection: String? = null
    var workFlowStatus: String? = null
    var createdBy: String? = null
    private var dateCreated: Date? = null
    private var dateLastUpdated: Date? = null
    var lastUpdatedBy: String? = null
    var validDistributionFlag: Boolean? = null
    /**
     * @return the flagInBulkloader
     */
    /**
     * @param flagInBulkloader the flagInBulkloader to set
     */
    var flagInBulkloader: Boolean? = null
    /**
     * @return the flagInMCZbase
     */
    /**
     * @param flagInMCZbase the flagInMCZbase to set
     */
    var flagInMCZbase: Boolean? = null
    /**
     * @return the flagAncilaryAlsoInMCZbase
     */
    /**
     * @param flagAncilaryAlsoInMCZbase the flagAncilaryAlsoInMCZbase to set
     */
    var flagAncilaryAlsoInMCZbase: Boolean? = null
    /**
     * @return the path
     */
    /**
     * @param path the path to set
     */
    var creatingPath // A path for image file, denormalized from Image.path for JPA query without join to Image.
            : String? = null
    /**
     * @return the creatingFilename
     */
    /**
     * @param creatingFilename the creatingFilename to set
     */
    var creatingFilename: String? = null
    var collectors: MutableSet<Collector?>? = HashSet(0)
    private var determinations: MutableSet<Determination?>? = HashSet<Determination?>(0)
    private var trackings: MutableSet<Tracking?>? = HashSet<Tracking?>(0)
    var numbers: MutableSet<Number?>? = HashSet(0)
    private var ICImages: MutableSet<ICImage?>? = HashSet<ICImage?>(0)
    private var specimenParts: MutableSet<SpecimenPart?>? = HashSet<SpecimenPart?>(0)
    private var georeferences: MutableSet<LatLong?>? = HashSet<LatLong?>(0)
    /**
     * @return the externalHistory
     */
    /**
     * @param externalHistory the externalHistory to set
     */
    var externalHistory: MutableSet<ExternalHistory?>? = HashSet<ExternalHistory?>(0)

    constructor() {
        setDefaults()
    }

    constructor(barcode: String?, typeStatus: String?, dateCreated: Date?) {
        validDistributionFlag = true
        this.barcode = barcode
        this.typeStatus = typeStatus
        if (dateCreated == null) {
            this.dateCreated = Date()
        } else {
            this.dateCreated = dateCreated.clone() as Date
        }
    }

    constructor(barcode: String?, drawerNumber: String?, typeStatus: String?,
                typeNumber: Long?, citedInPublication: String?, features: String?,
                family: String?, subfamily: String?, tribe: String?, genus: String?,
                specificEpithet: String?, subspecificEpithet: String?,
                infraspecificEpithet: String?, infraspecificRank: String?,
                authorship: String?, unNamedForm: String?,
                identificationQualifier: String?, identifiedBy: String?,
                country: String?, primaryDivison: String?, specificLocality: String?,
                verbatimLocality: String?,
                minimum_elevation: Long?, maximum_elevation: Long?, elev_units: String?,
                collectingMethod: String?, dateNos: String?, dateEmerged: String?,
                dateEmergedIndicator: String?, dateCollected: String?,
                dateCollectedIndicator: String?, collection: String?,
                specimenNotes: String?, lifeStage: String?, preparationType: String?,
                sex: String?, microhabitat: String?,
                habitat: String?, associatedTaxon: String?, questions: String?,
                inferences: String?, locationInCollection: String?,
                workFlowStatus: String?, createdBy: String?, dateCreated: Date?,
                dateLastUpdated: Date?, lastUpdatedBy: String?,
                validDistributionFlag: Boolean?, collectors: MutableSet<Collector?>?,
                determinations: MutableSet<Determination?>?, trackings: MutableSet<Tracking?>?,
                numbers: MutableSet<Number?>?, ICImages: MutableSet<ICImage?>?,
                specimenParts: MutableSet<SpecimenPart?>?) {
        this.barcode = barcode
        this.drawerNumber = drawerNumber
        this.typeStatus = typeStatus
        this.typeNumber = typeNumber
        this.citedInPublication = citedInPublication
        this.features = features
        family = family
        this.subfamily = subfamily
        this.tribe = tribe
        this.genus = genus
        this.specificEpithet = specificEpithet
        this.subspecificEpithet = subspecificEpithet
        this.infraspecificEpithet = infraspecificEpithet
        this.infraspecificRank = infraspecificRank
        this.authorship = authorship
        this.unNamedForm = unNamedForm
        this.identifiedBy = identifiedBy
        this.country = country
        this.primaryDivison = primaryDivison
        this.specificLocality = specificLocality
        this.verbatimLocality = verbatimLocality
        //this.verbatimElevation = verbatimElevation;
        this.minimum_elevation = minimum_elevation
        this.maximum_elevation = maximum_elevation
        this.elev_units = elev_units
        this.collectingMethod = collectingMethod
        this.dateNos = dateNos
        this.dateEmerged = dateEmerged
        this.dateEmergedIndicator = dateEmergedIndicator
        this.dateCollected = dateCollected
        this.dateCollectedIndicator = dateCollectedIndicator
        this.collection = collection
        this.specimenNotes = specimenNotes
        this.lifeStage = lifeStage
        this.sex = sex
        //this.preparationType = preparationType;
        this.habitat = habitat
        this.microhabitat = microhabitat
        this.associatedTaxon = associatedTaxon
        this.questions = questions
        this.inferences = inferences
        this.locationInCollection = locationInCollection
        this.workFlowStatus = workFlowStatus
        this.createdBy = createdBy
        if (dateCreated != null) {
            this.dateCreated = dateCreated.clone() as Date
        }
        if (dateLastUpdated != null) {
            this.dateLastUpdated = dateLastUpdated.clone() as Date
        }
        this.lastUpdatedBy = lastUpdatedBy
        this.validDistributionFlag = validDistributionFlag
        this.collectors = collectors
        //allie new
//collectors.add(new Collector(this, "the name"));
//
        this.determinations = determinations
        this.trackings = trackings
        this.numbers = numbers
        this.ICImages = ICImages
        this.specimenParts = specimenParts
    }

    /**
     * Set default values for a new specimen object with no other data.
     */
    fun setDefaults() { // NOTE: Any default set here should also be cleared in clearDefaults
// or searches by example may not return expected results.
        typeStatus = STATUS_NOT_A_TYPE
        validDistributionFlag = true
        flagInBulkloader = false
        flagInMCZbase = false
        flagAncilaryAlsoInMCZbase = false
        //this.preparationType = "Pinned";
//allie change
//this.natureOfId = NatureOfId.LEGACY;
        natureOfId = NatureOfId.EXPERT_ID
        //collectors.add(new Collector(this,"first collector"));
/*
		if (this.verbatimCollection==null) { this.verbatimCollection = ""; }
		if (this.verbatimCollector==null) { this.verbatimCollector = ""; }
		if (this.verbatimLocality==null) { this.verbatimLocality = ""; }
		if (this.verbatimNumbers==null) { this.verbatimNumbers = ""; }
		if (this.verbatimUnclassifiedText==null) { this.verbatimUnclassifiedText = ""; }
		*/
// this.dateCreated = new Date();
    }

    /**
     * Clear the default values for a new specimen object, as in one that
     * is to be used as the search criteria for a search by pattern.
     */
    fun clearDefaults() { // Note: these could also be ignored in SpecimenLifeCycle.findByExampleLike().
        typeStatus = null
        validDistributionFlag = null
        flagInBulkloader = null
        flagInMCZbase = null
        flagAncilaryAlsoInMCZbase = null
        //this.preparationType = null;
        natureOfId = null
    }

    /**
     * non-zero padded catalog number extracted from the barcode, equivalent to
     * arctos/MCZbase cat_num for lepidoptera.
     *
     * @return numeric part of barcode without zero padding
     */
    val catNum: String
        get() = Integer.toString(barcode!!.substring(8).toInt())

    fun getDrawerNumber(): String? {
        return drawerNumber
    }

    fun setDrawerNumber(drawerNumber: String?) {
        this.drawerNumber = drawerNumber
        if (this.drawerNumber != null && this.drawerNumber!!.length > MetadataRetriever.getFieldLength(Specimen::class.java, "DrawerNumber")) {
            this.drawerNumber = this.drawerNumber!!.substring(0, MetadataRetriever.getFieldLength(Specimen::class.java, "DrawerNumber"))
        }
    }

    fun getSubfamily(): String? {
        return subfamily
    }

    fun setSubfamily(subfamily: String?) {
        this.subfamily = subfamily
        if (this.subfamily != null) {
            this.subfamily = this.subfamily!!.trim { it <= ' ' }
        }
    }

    fun getTribe(): String? {
        return tribe
    }

    fun setTribe(tribe: String?) {
        this.tribe = tribe
        if (this.tribe != null) {
            this.tribe = this.tribe!!.trim { it <= ' ' }
        }
    }

    fun getGenus(): String? {
        return genus
    }

    fun setGenus(genus: String?) {
        this.genus = genus
        if (this.genus != null) {
            this.genus = this.genus!!.trim { it <= ' ' }
        }
    }

    fun getSpecificEpithet(): String? {
        return specificEpithet
    }

    fun setSpecificEpithet(specificEpithet: String?) {
        this.specificEpithet = specificEpithet
        if (this.specificEpithet != null) {
            this.specificEpithet = this.specificEpithet!!.trim { it <= ' ' }
        }
    }

    fun getSubspecificEpithet(): String? {
        return subspecificEpithet
    }

    fun setSubspecificEpithet(subspecificEpithet: String?) {
        this.subspecificEpithet = subspecificEpithet
        if (this.subspecificEpithet != null) {
            this.subspecificEpithet = this.subspecificEpithet!!.trim { it <= ' ' }
        }
    }

    fun getInfraspecificEpithet(): String? {
        return infraspecificEpithet
    }

    fun setInfraspecificEpithet(infraspecificEpithet: String?) {
        this.infraspecificEpithet = infraspecificEpithet
        if (this.infraspecificEpithet != null) {
            this.infraspecificEpithet = this.infraspecificEpithet!!.trim { it <= ' ' }
        }
    }

    fun getInfraspecificRank(): String? {
        return infraspecificRank
    }

    fun setInfraspecificRank(infraspecificRank: String?) {
        this.infraspecificRank = infraspecificRank
        if (this.infraspecificRank != null) {
            this.infraspecificRank = this.infraspecificRank!!.trim { it <= ' ' }
        }
    }

    fun getAuthorship(): String? {
        return authorship
    }

    fun setAuthorship(authorship: String?) {
        this.authorship = authorship
        if (this.authorship != null) {
            this.authorship = this.authorship!!.trim { it <= ' ' }
        }
    }

    fun getUnNamedForm(): String? {
        return unNamedForm
    }

    fun setUnNamedForm(unNamedForm: String?) {
        this.unNamedForm = unNamedForm
        if (this.unNamedForm != null) {
            this.unNamedForm = this.unNamedForm!!.trim { it <= ' ' }
        }
    }

    //	public String getVerbatimElevation() {
//		return this.verbatimElevation;
//	}
//
//	public void setVerbatimElevation(String verbatimElevation) {
//		this.verbatimElevation = verbatimElevation;
//	}

    /**
     * @return the minimum_elevation
     */
    /**
     * @param minimum_elevation the minimum_elevation to set
     */
    var minimumElevationSt: String?
        get() = if (minimum_elevation == null) {
            null
        } else minimum_elevation.toString()
        set(minimum_elevation) {
            if (minimum_elevation == null || minimum_elevation.trim { it <= ' ' }.length == 0) {
                this.minimum_elevation = null
            } else {
                this.minimum_elevation = minimum_elevation.toLong()
            }
        }

    /**
     * @return the maximum_elevation
     */
    /**
     * @param maximum_elevation the maximum_elevation to set
     */
    var maximumElevationSt: String?
        get() = if (maximum_elevation == null) {
            null
        } else maximum_elevation.toString()
        set(maximum_elevation) {
            if (maximum_elevation == null || maximum_elevation.trim { it <= ' ' }.length == 0) {
                this.maximum_elevation = null
            } else {
                this.maximum_elevation = maximum_elevation.toLong()
            }
        }

    fun getDateCreated(): Date? {
        return dateCreated
    }

    fun setDateCreated(dateCreated: Date?) {
        if (dateCreated == null) {
            this.dateCreated = null
        } else {
            this.dateCreated = dateCreated.clone() as Date
            if (dateLastUpdated == null) {
                dateLastUpdated = this.dateCreated!!.clone() as Date
            }
        }
    }

    fun getDateLastUpdated(): Date? {
        return dateLastUpdated
    }

    fun setDateLastUpdated(dateLastUpdated: Date?) {
        if (dateLastUpdated == null) {
            this.dateLastUpdated = null
        } else {
            this.dateLastUpdated = dateLastUpdated.clone() as Date
        }
    }

    fun getDeterminations(): MutableSet<Determination?>? {
        return determinations
    }

    fun setDeterminations(determinations: MutableSet<Determination?>?) {
        this.determinations = determinations
    }

    fun getTrackings(): MutableSet<Tracking?>? {
        return trackings
    }

    fun setTrackings(trackings: MutableSet<Tracking?>?) {
        this.trackings = trackings
    }

    fun getICImages(): MutableSet<ICImage?>? {
        return ICImages
    }

    fun setICImages(ICImages: MutableSet<ICImage?>?) {
        this.ICImages = ICImages
    }

    /**
     * @return the specimenParts
     */
    fun getSpecimenParts(): MutableSet<SpecimenPart?>? {
        return specimenParts
    }

    /**
     * @param specimenParts the specimenParts to set
     */
    fun setSpecimenParts(specimenParts: MutableSet<SpecimenPart?>?) {
        this.specimenParts = specimenParts
    }

    // TODO: remove the following code if possible
    var latLong: MutableSet<
import edu.harvard.mcz.imagecapture.entity.LatLong?>?
        get() {
            if (georeferences == null) {
                georeferences = HashSet<LatLong?>()
            }
            // TODO: remove the following code if possible
            if (georeferences!!.isEmpty()) {
                val georef = LatLong()
                georef.setSpecimen(this)
                georeferences!!.add(georef)
            }
            return georeferences
        }
        set(latlongs) {
            georeferences = latlongs
        }

    val isStateDone: Boolean
        get() {
            var result = false
            if (workFlowStatus == WorkFlowStatus.STAGE_DONE) {
                result = true
            }
            return result
        }

    val loadFlags: String
        get() {
            var result = "Unexpected State"
            if (!flagInBulkloader!! && !flagInMCZbase!! && !flagAncilaryAlsoInMCZbase!!) {
                result = "In DataShot"
            }
            if (flagInBulkloader!! && !flagInMCZbase!! && !flagAncilaryAlsoInMCZbase!!) {
                result = "In Bulkloader"
            }
            if (flagInBulkloader!! && flagInMCZbase!! && !flagAncilaryAlsoInMCZbase!!) {
                result = "Adding Image and Ids."
            }
            if (flagInBulkloader!! && flagInMCZbase!! && flagAncilaryAlsoInMCZbase!!) {
                result = WorkFlowStatus.STAGE_DONE
            }
            return result
        }

    fun attachNewPart() {
        val newPart = SpecimenPart()
        newPart.setPreserveMethod(Singleton.getProperties().getProperties().getProperty(ImageCaptureProperties.Companion.KEY_DEFAULT_PREPARATION))
        newPart.setSpecimen(this)
        val spls = SpecimenPartLifeCycle()
        try {
            spls.persist(newPart)
            getSpecimenParts()!!.add(newPart)
        } catch (e1: SaveFailedException) {
            log!!.error(e1.message, e1)
        }
    }

    /**
     * Set the value of specificLocality to a string that has a meaning
     * of there being no specific locality data.  MCZbase requires a
     * non-null value for specific locality on bulkloader ingest.
     */
    fun noSpecificLocalityData() {
        specificLocality = "[no specific locality data]"
    }

    /**
     * Assemble relevant fields of the current identification into a scientific name.
     *
     * @return
     */
    fun assembleScientificName(): String {
        val result = StringBuffer()
        result.append(genus).append(" ").append(specificEpithet).append(" ").append(infraspecificRank).append(" ").append(infraspecificEpithet)
        return result.toString().trim { it <= ' ' }
    }

    companion object {
        val STATUS_NOT_A_TYPE: String? = "Not a Type"
        private val log = LogFactory.getLog(Specimen::class.java)
        private const val serialVersionUID = -1321141594439433313L
    }
}
