package edu.harvard.mcz.imagecapture.entity


import java.io.Serializable

// Generated Feb 27, 2009 8:34:09 AM by Hibernate Tools 3.2.2.GA
/**
 * Template generated by hbm2java
 */
class Template : Serializable {
    var templateId: String? = null
    var name: String? = null
    var imageSizeX: Int? = null
    var imageSizeY: Int? = null
    var barcodePositionX: Int? = null
    var barcodePositionY: Int? = null
    var barcodeSizeX: Int? = null
    var barcodeSizeY: Int? = null
    var specimenPositionX: Int? = null
    var specimenPositionY: Int? = null
    var specimenSizeX: Int? = null
    var specimenSizeY: Int? = null
    var textPositionX: Int? = null
    var textPositionY: Int? = null
    var textSizeX: Int? = null
    var textSizeY: Int? = null
    var labelPositionX: Int? = null
    var labelPositionY: Int? = null
    var labelSizeX: Int? = null
    var labelSizeY: Int? = null
    var utLabelPositionX: Int? = null
    var utLabelPositionY: Int? = null
    var utLabelSizeX: Int? = null
    var utLabelSizey: Int? = null
    var utBarcodePositionX: Int? = null
    var utBarcodePositionY: Int? = null
    var utBarcodeSizeX: Int? = null
    var utBarcodeSizeY: Int? = null
    var editable = false
    private var referenceImage: ICImage? = null

    constructor() {}
    constructor(templateId: String?) {
        this.templateId = templateId
    }

    constructor(templateId: String?, name: String?, imageSizeX: Int?,
                imageSizeY: Int?, barcodePositionX: Int?,
                barcodePositionY: Int?, barcodeSizeX: Int?,
                barcodeSizeY: Int?, specimenPositionX: Int?,
                specimenPositionY: Int?, specimenSizeX: Int?,
                specimenSizeY: Int?, textPositionX: Int?,
                textPositionY: Int?, textSizeX: Int?, textSizeY: Int?,
                labelPositionX: Int?, labelPositionY: Int?, labelSizeX: Int?,
                labelSizeY: Int?, utLabelPositionX: Int?,
                utLabelPositionY: Int?, utLabelSizeX: Int?, utLabelSizey: Int?,
                editable: Boolean, referenceImage: ICImage?,
                utBarcodePositionY: Int?, utBarcodeSizeX: Int?, utBarcodeSizeY: Int?
    ) {
        this.templateId = templateId
        this.name = name
        this.imageSizeX = imageSizeX
        this.imageSizeY = imageSizeY
        this.barcodePositionX = barcodePositionX
        this.barcodePositionY = barcodePositionY
        this.barcodeSizeX = barcodeSizeX
        this.barcodeSizeY = barcodeSizeY
        this.specimenPositionX = specimenPositionX
        this.specimenPositionY = specimenPositionY
        this.specimenSizeX = specimenSizeX
        this.specimenSizeY = specimenSizeY
        this.textPositionX = textPositionX
        this.textPositionY = textPositionY
        this.textSizeX = textSizeX
        this.textSizeY = textSizeY
        this.labelPositionX = labelPositionX
        this.labelPositionY = labelPositionY
        this.labelSizeX = labelSizeX
        this.labelSizeY = labelSizeY
        this.utLabelPositionX = utLabelPositionX
        this.utLabelPositionY = utLabelPositionY
        this.utLabelSizeX = utLabelSizeX
        this.utLabelSizey = utLabelSizey
        utBarcodePositionX = utLabelPositionX
        this.utBarcodePositionY = utLabelPositionY
        this.utBarcodeSizeX = utBarcodeSizeX
        this.utBarcodeSizeY = utBarcodeSizeY
        this.editable = editable
        this.referenceImage = referenceImage
    }

    fun getReferenceImage(): ICImage? {
        return referenceImage
    }

    fun setReferenceImage(referenceImage: ICImage?) {
        this.referenceImage = referenceImage
    }

    companion object {
        private const val serialVersionUID = -7457138600715862183L
    }
}
