package edu.harvard.mcz.imagecapture.entity


import java.io.Serializable
import java.util.*

// Generated Jan 23, 2009 8:12:35 AM by Hibernate Tools 3.2.2.GA
/**
 * Tracking generated by hbm2java
 */
class Tracking : Serializable {
    var trackingId: Long? = null
    private var specimen: Specimen? = null
    var user: String? = null
    var eventType: String? = null
    private var eventDateTime: Date? = null

    /**
     * Utility constructor if no date is needed
     */
    constructor() {}

    constructor(specimen: Specimen?, eventDateTime: Date?) {
        this.specimen = specimen
        if (eventDateTime == null) {
            this.eventDateTime = Date()
        } else {
            this.eventDateTime = eventDateTime.clone() as Date
        }
    }

    @JvmOverloads
    constructor(specimen: Specimen?, user: String?, eventType: String?,
                eventDateTime: Date? = null) : this(specimen, eventDateTime) {
        this.user = user
        this.eventType = eventType
    }

    fun getSpecimen(): Specimen? {
        return specimen
    }

    fun setSpecimen(specimen: Specimen?) {
        this.specimen = specimen
    }

    fun getEventDateTime(): Date? {
        return eventDateTime
    }

    fun setEventDateTime(eventDateTime: Date?) {
        if (eventDateTime == null) {
            this.eventDateTime = null
        } else {
            this.eventDateTime = eventDateTime.clone() as Date
        }
    }

    companion object {
        private const val serialVersionUID = 3045144335474980280L
    }
}
